#!/usr/bin/env python3
"""Extract a compact, alphabetically indexed int8 model from word2vec binary."""

import argparse
import math
import re
import struct


WORD_RE = re.compile(r"^[a-z][a-z'-]*$")
MAX_RUNTIME_VOCAB = 4096
RUNTIME_DIMENSION = 50


def read_token(handle):
    chars = bytearray()
    while True:
        value = handle.read(1)
        if not value:
            return None
        if value in (b" ", b"\n", b"\r", b"\t"):
            return bytes(chars)
        chars.extend(value)


def quantize(values):
    norm = math.sqrt(sum(value * value for value in values))
    if norm == 0.0:
        return [0] * len(values)
    result = []
    for value in values:
        scaled = value / norm * 127.0
        rounded = int(scaled + 0.5) if scaled >= 0 else int(scaled - 0.5)
        result.append(max(-127, min(127, rounded)))
    return result


def load_records(path, requested_count, expected_dimension, max_word_length):
    records = {}
    with open(path, "rb") as handle:
        header = handle.readline().decode("ascii").strip().split()
        if len(header) != 2:
            raise ValueError("word2vec binary header must contain vocabulary and dimension")
        vocabulary_count, dimension = int(header[0]), int(header[1])
        if dimension != expected_dimension:
            raise ValueError(
                "model dimension is %d, expected %d" % (dimension, expected_dimension)
            )

        vector_bytes = dimension * 4
        for _ in range(vocabulary_count):
            token = read_token(handle)
            if token is None:
                break
            vector_data = handle.read(vector_bytes)
            if len(vector_data) != vector_bytes:
                raise ValueError("truncated vector for %r" % token)
            handle.read(1)

            try:
                word = token.decode("ascii").lower()
            except UnicodeDecodeError:
                continue
            if len(word) == 0 or len(word) > max_word_length or not WORD_RE.match(word):
                continue
            if word in records:
                continue
            values = struct.unpack("<%df" % dimension, vector_data)
            records[word] = quantize(values)
            if len(records) >= requested_count:
                break

    selected = sorted(records.items())
    if not selected:
        raise ValueError("no valid ASCII words were found in the model")
    return selected[:requested_count]


def c_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_header(path, records, dimension, max_word_length):
    words = [word for word, _ in records]
    vectors = [vector for _, vector in records]
    with open(path, "w", encoding="ascii", newline="\n") as output:
        output.write("#ifndef SEMANTLE_PLUS_MODEL_DATA_H\n")
        output.write("#define SEMANTLE_PLUS_MODEL_DATA_H\n\n")
        output.write("/* Generated by tools/extract_word2vec.py; do not edit. */\n")
        output.write("#define MODEL_WORD_COUNT %d\n" % len(words))
        output.write("#define MODEL_VECTOR_DIMENSION %d\n" % dimension)
        output.write("#define MODEL_MAX_WORD_LENGTH %d\n\n" % max_word_length)
        output.write(
            "static const char kModelWords[MODEL_WORD_COUNT][MODEL_MAX_WORD_LENGTH + 1] = {\n"
        )
        for word in words:
            output.write("    %s,\n" % c_string(word))
        output.write("};\n\n")
        output.write(
            "static const signed char kModelVectors[MODEL_WORD_COUNT][MODEL_VECTOR_DIMENSION] = {\n"
        )
        for vector in vectors:
            output.write("    {")
            output.write(", ".join(str(value) for value in vector))
            output.write("},\n")
        output.write("};\n\n#endif\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="word2vec -binary output")
    parser.add_argument("--output", required=True, help="generated C header")
    parser.add_argument("--vocab-size", type=int, default=4096)
    parser.add_argument("--dim", type=int, default=50)
    parser.add_argument("--max-word-length", type=int, default=23)
    args = parser.parse_args()
    if args.vocab_size < 50:
        raise SystemExit("--vocab-size must be at least 50")
    if args.vocab_size > MAX_RUNTIME_VOCAB:
        raise SystemExit("--vocab-size must be at most %d for the 1 MB target" %
                         MAX_RUNTIME_VOCAB)
    if args.dim != RUNTIME_DIMENSION:
        raise SystemExit("--dim must remain %d for the runtime engine" % RUNTIME_DIMENSION)
    records = load_records(args.input, args.vocab_size, args.dim, args.max_word_length)
    write_header(args.output, records, args.dim, args.max_word_length)
    print("extracted %d words x %d dimensions into %s" %
          (len(records), args.dim, args.output))


if __name__ == "__main__":
    main()
